name: tabib_soft_company
description: "A new Flutter project."


publish_to: 'none'


version: 1.0.0+2

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 # ------------ Icons ------------
  cupertino_icons: ^1.0.6

  

  # ------------ UI --------------
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  modal_progress_hud_nsn: ^0.5.1
  carousel_slider: ^5.0.0
  skeletonizer: ^1.4.2
  fluttertoast: ^8.2.8

  

  # ------------ Images ------------
  flutter_svg: ^2.0.10+1


  # ------------ Firebase ----------
  firebase_core: ^3.5.0
  firebase_remote_config: ^5.1.2
  firebase_crashlytics: ^4.1.2
  

  # ---------- Local Storage ----------
  shared_preferences: ^2.3.2



  # ---------- Localization ----------
  flutter_localization: ^0.2.2



  # --------- State Management ---------
  flutter_bloc: ^8.1.6 
  get_it: ^7.7.0 
  freezed: ^2.5.7 
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0 
  json_annotation: ^4.9.0 
  build_runner: ^2.4.12
  package_info_plus: ^8.0.2
  rename: ^3.0.2



  # ----------- Network --------------
  dio: ^5.7.0 
  pretty_dio_logger: ^1.4.0 
  retrofit: ^4.4.1 
  retrofit_generator: ^9.1.2
  connectivity_plus: ^6.0.5 
  cached_network_image: ^3.4.1 
  url_launcher: ^6.3.0
  fancy_shimmer_image: ^2.0.3 


  # ------------ Utils --------------
  easy_localization: ^3.0.7 


  # ------------ Security -------------
  flutter_secure_storage: ^9.2.2
  device_info_plus: ^11.3.0
  equatable: ^2.0.7
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/pngs/
    - assets/images/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
